[build]
aptPackages = [
  "libglib2.0-0",
  "libgobject-2.0-0",
  "libcairo2",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libpangoft2-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libffi-dev",
  "libharfbuzz-subset0",
  "shared-mime-info",
  "fontconfig"
]

[deploy]
aptPackages = [
  "libglib2.0-0",
  "libgobject-2.0-0",
  "libcairo2",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libpangoft2-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libffi-dev",
  "libharfbuzz-subset0",
  "shared-mime-info",
  "fontconfig"
]
